### PR TITLE
Fr

### PR DESCRIPTION
**Pull request by GitHub2Sam**

### CODE REVIEW

**Comment by bennuttall** [comment]
Hi - thanks for the translation.

I'm going to close this PR as we don't want to replace the original version with a French version. Instead, we can point readers at a French translation at https://github.com/GitHub2Sam/web-server-wordpress

Thanks again

/cc @helenlynn @LizUpton

**Comment by GitHub2Sam** [comment]
Hi,

thanks ;) sorry I'm a big noob with GitHub, I first cerated a fork, then a
branch named "fr" to do the translations. Liz told me this :
Hi Samuel

Thank you very much for the offer; we’d be very grateful for the help. The
resources are all Creative Commons licensed; if you were to create a fork
on GitHub (links to each resource’s GitHub repository are at the bottom of
each resource) and let us know when you’re done, we’ll look at how to draw
people’s attention to the translations.

Liz
--
Head of Communications

Raspberry Pi Foundation

So I thought I might have to merge the fr to the master but got confused
and did a PR just to say hi ;) To be honest, this is my first try, I have
to actually do the tutorial to see what will be the Pi/WordPress messages
on the screen and might have to update some of the files accordingly (and
maybe some typo, french...).

So I would like to keep on translating to help french people/teachers to
get to know and have fun with the Pi - or even open a class etc- so could
you please tell me how to do so : should I keep on doing like I just did
minus the PR ? - Should I send you guys every fork I made ?

Best regards,

Sam.



2015-06-15 22:43 GMT+02:00 Ben Nuttall <notifications@github.com>:

**Comment by bennuttall** [comment]
Hi Sam

Yes - that's fine. Create a fork, work on the fork and just email us the link when it's done.

Thanks

**Comment by GitHub2Sam** [comment]
Hi Ben,

understood, will do - pretty busy these days family+work but I should be
able to translate some of the worksheet soon.

Have a nice day !

Cheers

2015-06-16 11:39 GMT+02:00 Ben Nuttall <notifications@github.com>:

**Pull request closed without merging**
